### ISSUE TITLE
4.13-4.20 周报

### ISSUE THREAD

**Issue by donghaiwang** [OpenHUTB/customs#14]
请按照下面格式每周写好周报

张三：2023.03.30~2023.04.6
本周工作总结：进行数据平台SDK及客户端开发测试，参与2.03需求开发
进展情况：1.修改原来的数据平台SDK的实现与需求不一致的情况，即和前端web功能不一致的情况；-close
2.进行最新实现功能的自测；-close
3.提交修改后的代码进行测试；-50%
遇到的问题：1.

下周工作计划：
任务：数据平台SDK
工作内容：1.监控并维护上线的数据SDK运行（3.7）；
2. 跟踪项目详情中可以看见每个数据ID进度的线上情况（3.7-3.9）；
3. 查看及参与标注平台2.04需求中的盘古工具链后端接口需求的开发（3.7-3.12）；

**Comment by eduujspeng** [comment]
周易鹏：2023.04.13~2023.04.20
本周工作总结：进行人脸口罩的检测与识别
进展情况：
1.采用retinaface进行人脸检测； -close
2.采用facenet进行人脸识别； -50%

遇到的问题：
1.口罩人脸识别过拟合，对于正常不带口罩人脸识别错误率高

下周工作计划：
1. 解决facenet过拟合问题；
2. 可视化展示

**Comment by luoxi4563** [comment]
谭孝文：2023.04.13~2023.04.20
本周工作总结：修改人脸识别部分中的人脸检测模型，并对效果进行测试
进展情况：1.将原来的MTCNN人脸检测网络修改为效果更好的SCRFD-10GF人脸检测网络； -close
2.自行测试修改后代码的效果。 -close

下周工作计划：
任务：优化人脸识别效果
工作内容：将原有的基于余弦相似度的人脸比较方法修改为基于欧式距离的人脸比较方法。

**Comment by coding-ssy** [comment]
宋书越：2023.04.13~2023.04.20
本周工作总结：修改多目标追踪代码与特征提取代码，使其能够直接导出每个人的步态轮廓图。
进展情况：1.根据多目标追踪算法记录视频中每个人在视频每一帧的位置坐标；
2.根据得到的位置坐标对视频人像剪切得到每个人的步态序列；
3.使用Mask_RCNN模型对每个人的步态序列进行背景删除得到每个人的步态轮廓图。
遇到的问题：将视频经过两个模型处理后得到的步态序列清晰度会下降，目前未发现原因。
下周工作计划：
工作内容：解决之前的问题，继续收集数据进行测试。

**Comment by maninbule** [comment]
李强：2023.04.13~2023.04.20
本周工作总结：整合步态识别的代码到系统中，学习QTWebengine模块
进展情况：目前系统关于展示步态识别的功能展示正在尝试集成
遇到的问题：环境配置还没解决，导致在QT中不能做到调用步态识别的输入输出
下周工作计划：
工作内容：
1.将步态识别进行初步集成
2.尝试用QTWebengine模块在客户端中集成网页展示功能

**Comment by nuonuo0426** [comment]
廖倩倩：2023.04.13~2023.04.20
本周工作总结：跑代码、找数据集
进展情况：
1、找了有关DFW伪装数据集得代码。并已跑通
2、找了人脸数据库的代码，跑通
3、最后跑了有关行人属性的代码

问题：
1、DFW的代码可以跑通，但是由于没有数据集，所以，没有结果
2、人脸数据库比对的代码，可以跑通，但是由于没有找到该代码的数据库，所以无法进行下一步操作

下周工作计划：
1、看懂行人属性识别的代码
