### ISSUE TITLE
周报

### ISSUE THREAD

**Issue by donghaiwang** [OpenHUTB/customs#6]
请按照下面格式每周写好周报

张三：2023.03.30~2023.04.6
本周工作总结：进行数据平台SDK及客户端开发测试，参与2.03需求开发
进展情况：1.修改原来的数据平台SDK的实现与需求不一致的情况，即和前端web功能不一致的情况；-close
                  2.进行最新实现功能的自测；-close
                  3.提交修改后的代码进行测试；-50%
遇到的问题：1. 

下周工作计划：
任务：数据平台SDK
工作内容：1.监控并维护上线的数据SDK运行（3.7）；
                  2. 跟踪项目详情中可以看见每个数据ID进度的线上情况（3.7-3.9）；
                  3. 查看及参与标注平台2.04需求中的盘古工具链后端接口需求的开发（3.7-3.12）；

**Comment by eduujspeng** [comment]
周易鹏：2023.03.30~2023.04.06
本周工作总结：实现在人脸检测之后对人脸进行识别
进展情况：
1. 利用MTCNN进行人脸检测和人脸矫正，使人脸眼睛处于水平位置
2. 利用Facenet进行人脸距离判断，实现人脸识别
3. 进行代码测试和提交
问题：
1.MTCNN人脸遮挡识别不强
2.Facenet人脸遮挡误判
下周工作计划：
修正MTCNN人脸遮挡识别能力不强问题

**Comment by coding-ssy** [comment]
宋书越：2023.03.30~2023.04.6
本周工作总结：修改GaitGL代码，使其能够按照自行设置的文件路径导入数据。
进展情况：1.理清GaitGL各模块代码间的关系；
2.使用debug方式从代码运行开始修改有关文件路径的部分知道代码运行结束。
下周工作计划：
工作内容：修改GaitGL代码使其能够针对实际场景进行应用。

**Comment by luoxi4563** [comment]
谭孝文：2023.04.06~2023.04.13
本周工作总结：利用facenet-pytorch实现初步的人脸识别需求
进展情况：1.调用python包实现实时的人脸识别及人脸录入；-close
2.完成人脸识别功能的自测；-close
遇到的问题：1.人脸检测模块检测准确率不高，容易发生漏检情况

下周工作计划：替换人脸识别流程中的人脸检测模块
任务：提高人脸检测准确率，减少漏检情况发生
工作内容：将原来的MTCNN人脸检测算法替换为效果更好的yolov5-face人脸检测算法

**Comment by coding-ssy** [comment]
宋书越：2023.04.06~2023.04.13
本周工作总结：修改GaitGL代码，使其能够进行步态图像比对。
进展情况：1.将步态数据分为基础库和验证库；
2.通过欧式距离进行比对最终输出验证库中每个步态序列对应的身份。
下周工作计划：
工作内容：修改特征提取模型代码。

**Comment by nuonuo0426** [comment]
廖：2023.04.06〜2023.04.13
本周：查找伪装的数据集---close
运行了YOLOV5代码；---close
下周计划：
工作内容：运行DWF数据集有关的代码

**Comment by eduujspeng** [comment]
周易鹏：2023.04.06~2023.04.13
本周工作总结：对MTCNN人脸检测模型进行口罩人脸训练
进展情况：
1、单人脸口罩检测识别率达到99%，接近完美

问题：
1、多人脸口罩检测识别率有待提升，漏检和错检率较高
2、人脸矫正部分侧脸人眼处于水平位置，不能矫正为正脸图像

下周工作计划：
1、修正MTCNN多人脸遮挡识别能力不强问题
2、矫正人脸图像，使其为正脸图像

**Comment by maninbule** [comment]
李强：2023.04.06~2023.04.13
本周工作总结：对系统进行了数据展示效果改进
进展情况：
1、能够动态显示数据变化过程
2、能够以较快的速度展示模型生成的数据，以图表形式展示

问题：
1、目前整合系统还需要配置python不同算法所需要的环境，比较难配置

下周工作计划：
1、将python环境与c++的QT系统进行整合到一起
2、将图片选择，以及多页面图片进行整合到系统中
